<?php

// This is a compiled Agavi configuration file
// Compiled from: C:/www/web-features/app/config/action_filters.xml
// Generated by: AgaviFilterConfigHandler
// Date: 2010-10-07T14:38:01+0000

$filter = new AgaviExecutionTimeFilter();
$filter->initialize($this->context, array (
  'comment' => true,
  'output_types' => 
  array (
    0 => 'html',
  ),
));
$filters[] = $filter;

?>