<?php

// This is a compiled Agavi configuration file
// Compiled from: C:/www/web-features/app/modules/Default/config/autoload.xml
// Generated by: AgaviAutoloadConfigHandler
// Date: 2010-10-11T08:23:46+0000

return array (
  'WebfeaturesDefaultBaseAction' => 'C:\\www\\web-features\\app/modules/Default/lib/action/WebfeaturesDefaultBaseAction.class.php',
  'WebfeaturesDefaultBaseModel' => 'C:\\www\\web-features\\app/modules/Default/lib/model/WebfeaturesDefaultBaseModel.class.php',
  'WebfeaturesDefaultBaseView' => 'C:\\www\\web-features\\app/modules/Default/lib/view/WebfeaturesDefaultBaseView.class.php',
);

?>