<?php

// This is a compiled Agavi configuration file
// Compiled from: C:/www/web-features/app/config/compile.xml
// Generated by: AgaviCompileConfigHandler
// Date: 2010-10-11T08:23:45+0000

require('C:\\xampp\\php\\PEAR\\agavi\\util\\AgaviAttributeHolder.class.php');
require('C:\\xampp\\php\\PEAR\\agavi\\action\\AgaviAction.class.php');
require('C:\\xampp\\php\\PEAR\\agavi\\core\\AgaviContext.class.php');
require('C:\\xampp\\php\\PEAR\\agavi\\controller\\AgaviController.class.php');
require('C:\\xampp\\php\\PEAR\\agavi\\controller\\AgaviExecutionContainer.class.php');
require('C:\\xampp\\php\\PEAR\\agavi\\controller\\AgaviOutputType.class.php');
require('C:\\xampp\\php\\PEAR\\agavi\\filter\\AgaviFilter.class.php');
require('C:\\xampp\\php\\PEAR\\agavi\\filter\\AgaviDispatchFilter.class.php');
require('C:\\xampp\\php\\PEAR\\agavi\\filter\\AgaviExecutionFilter.class.php');
require('C:\\xampp\\php\\PEAR\\agavi\\filter\\AgaviFilterChain.class.php');
require('C:\\xampp\\php\\PEAR\\agavi\\renderer\\AgaviRenderer.class.php');
require('C:\\xampp\\php\\PEAR\\agavi\\request\\AgaviRequestDataHolder.class.php');
require('C:\\xampp\\php\\PEAR\\agavi\\request\\AgaviRequest.class.php');
require('C:\\xampp\\php\\PEAR\\agavi\\response\\AgaviResponse.class.php');
require('C:\\xampp\\php\\PEAR\\agavi\\routing\\AgaviRouting.class.php');
require('C:\\xampp\\php\\PEAR\\agavi\\storage\\AgaviStorage.class.php');
require('C:\\xampp\\php\\PEAR\\agavi\\user\\AgaviUser.class.php');
require('C:\\xampp\\php\\PEAR\\agavi\\view\\AgaviTemplateLayer.class.php');
require('C:\\xampp\\php\\PEAR\\agavi\\view\\AgaviView.class.php');

?>