<?php

// This is a compiled Agavi configuration file
// Compiled from: C:/www/web-features/app/modules/Default/config/config_handlers.xml
// Generated by: AgaviConfigHandlersConfigHandler
// Date: 2010-10-07T14:38:01+0000

return array (
)

?>