<?php

// This is a compiled Agavi configuration file
// Compiled from: C:/www/web-features/app/config/databases.xml
// Generated by: AgaviDatabaseConfigHandler
// Date: 2010-10-11T08:23:45+0000

$database = new AgaviDoctrineDatabase();
$this->databases['doctrine'] = $database;
$database->initialize($this, array (
  'dsn' => 'pgsql://root:root@localhost/webfeatures',
  'charset' => 'utf8',
  'options' => 
  array (
    'username' => 'root',
    'password' => 'root',
  ),
  'load_models' => 'C:\\www\\web-features\\app/models',
));
$this->defaultDatabaseName = 'doctrine';

?>